export const CONTACTLIST = {
    GET_CONTACTLIST_PENDING: 'GET_CONTACTLIST_PENDING',
    GET_CONTACTLIST_SUCCESS: 'GET_CONTACTLIST_SUCCESS',
    GET_CONTACTLIST_ERROR: 'GET_CONTACTLIST_ERROR',

    CONTACT_DETAIL_PENDING: 'CONTACT_DETAIL_PENDING',
    CONTACT_DETAIL_SUCCESS: 'CONTACT_DETAIL_SUCCESS',
    CONTACT_DETAIL_ERROR: 'CONTACT_DETAIL_ERROR',

    ADD_FAVOURITE: 'ADD_FAVOURITE',
    REMOVE_FAVOURITE: 'REMOVE_FAVOURITE',
}